spring.datasource.url=jdbc:postgresql://localhost:5432/grassroots_db
spring.datasource.username=postgres
spring.datasource.password=grassroots_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=grassroots-radar
server.port=8080

jwt.secret=Z3Jhc3Nyb290c3N1cGVyc2VjcmV0a2V5MjAyNG1ha2V0aGlzbG9uZ2Vub3VnaA==
jwt.expiration=86400000

cloudinary.url=cloudinary://placeholder:placeholder@placeholder